# Generated by Django 3.2.5 on 2021-07-17 07:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.SlugField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.SlugField(blank=True, editable=False, null=True)),
                ('image', models.ImageField(upload_to='movies/')),
                ('taller_video', models.URLField(blank=True, null=True)),
                ('relished_date', models.DateField(default=datetime.datetime.now)),
                ('producer_name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('actress_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('category', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='movies.category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movies',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Actress_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movies/actress/')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'verbose_name': 'Actress Images',
                'verbose_name_plural': 'Actress Images',
            },
        ),
    ]
