# Generated by Django 3.2.5 on 2021-07-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
